version: '3.8'

services:
    backend:
        restart: always
        command: gunicorn backend.wsgi --bind 0.0.0.0:8000
        build:
            context: ./backend
            dockerfile: Dockerfile
        expose:
            - "8000"

    nginx:
        command: sleep 60; nginx
        build: ./nginx
        ports:
            - "8008:80"
        depends_on:
            - backend

