version: '3.8'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        depends_on:
            - backend
        expose:
            - 3000

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        expose:
            - 8000

    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - backend
            - frontend

