version: '3.8'

services:
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web

    web:
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn --workers 3 -b 0.0.0.0:8000 backend.wsgi
        expose:
            - 8000
