version: '3.8'

services:
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web

    web:
        restart: always
        build:
            context: ./backend
            dockerfile: Dockerfile
        expose:
            - "8000"
