version: '3.8'

services:
    nginx:
        build: ./nginx
        ports:
            - "8008:80"
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        expose:
            - "8000"
