version: '3.8'

services:
    backend:
        restart: always
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        expose:
            - 8000
        networks:
            - nginx_network

    nginx:
        build: ./nginx
        ports:
            - "8008:80"
        depends_on:
            - backend
        networks:
            - nginx_network

networks:
    nginx_network:
        driver: bridge
